#!/bin/bash -l
#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 02:00:00
#SBATCH -J prokka_E745_pacbio
#SBATCH --mail-type=ALL
#SBATCH --mail-user=sebastian_ellwe@hotmail.com
#SBATCH --output=%x.%j.out

# Load Prokka module
module load bioinfo-tools
module load prokka/1.45-5b58020

prokka --force\
  --outdir /home/sebase/Genome-Analysis/analyses/03_gene_annotation \
  --prefix E745_pacbio \
  --cpus 1 \
  /home/sebase/Genome-Analysis/analyses/02_genome_assembly/pacbio/E745_pacbio.contigs.fasta
